apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-storage
  namespace: openebs
spec:
  pools:
    - nodeSelector:
        kubernetes.io/hostname: "worker-gpu-1"
      dataRaidGroups:
      - blockDevices:
          - blockDeviceName: "blockdevice-38003102259819786b098db5d603ead6"
      poolConfig:
        dataRaidGroupType: "stripe"

    - nodeSelector:
        kubernetes.io/hostname: "worker-gpu-3" 
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: "blockdevice-27cb4f9b011d8cf24b091aa2803475fa"
            - blockDeviceName: "blockdevice-e853854d65fb9b41e85f7ef5ffa2063a"
      poolConfig:
        dataRaidGroupType: "stripe"

    - nodeSelector:
        kubernetes.io/hostname: "worker-gpu-7"
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: "blockdevice-8179ead6c96cef9f75b615ab91e0a19a"
            - blockDeviceName: "blockdevice-b57845d65983b0218b4803c00438e4c6"
      poolConfig:
        dataRaidGroupType: "stripe"

    - nodeSelector:
        kubernetes.io/hostname: "worker-gpu-2"
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: "blockdevice-6662057aae0da5e440480125718fabce"
      poolConfig:
        dataRaidGroupType: "stripe"


