# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"cstor-csi"},"parameters":{"cas-type":"cstor","cstorPoolCluster":"cstor-storage","replicaCount":"3"},"provisioner":"cstor.csi.openebs.io"}
  name: sc-ia-01
parameters:
  cas-type: cstor
  cstorPoolCluster: cstor-storage
  replicaCount: "3"
provisioner: cstor.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: Immediate

